### ISSUE TITLE
performance degradation in case of existing index

### ISSUE THREAD

**Issue by arnitolog** [confluentinc/kafka-connect-elasticsearch#332] opened 2019-08-21 12:25 UTC
Hello.
I was able to send ~8k docs per seconds when I started 1 task. And this task initiates a new index creation. But when I add any additional number of tasks, or just a create connector which sends data to the existing index the sending rate is never cross 300-500 docs/s level.
![image](https://user-images.githubusercontent.com/34036079/63430452-47dcd680-c425-11e9-91dd-a73020128c89.png)

**Comment by arnitolog** [comment] 2019-09-05 14:35
Hello, is there any way to get the artifact with the fix? Or I need to compile it manually?

**Comment by kkonstantine** [comment] 2019-09-06 00:35
There's no bugfix release yet with this fix. Compiling from source is definitely an option now that the fix was merged. Check the changelog of future bugfix releases to confirm that the fix is included. 

Closing the issue since the fix was merged in https://github.com/confluentinc/kafka-connect-elasticsearch/pull/340 and tests were conducted to show that the performance regression has been fixed. But feel free to re-open if the same or similar effect is still reproducible.

**Closed by kkonstantine** 2019-09-06 00:35 UTC
