### ISSUE TITLE
Flush timeout expired with unflushed records 

### ISSUE THREAD

**Issue by panda87** [confluentinc/kafka-connect-elasticsearch#103] opened 2017-07-24 08:52 UTC
Hi

Im using this plugin and when I started to send data to ES I got the following error (multiple times).
Kafka version: 0.10.2.1
Kafka-connect-es plugin version: 3.2.2

I can see the other topics (config, storage) which index new events and only this offset topic remains empty. I also can't see that in kafka-manager consumers section.

I dont see any error from the kafka cluster.

Does anyone know what can cause this and how can i solve it without upgrading my kafka cluster version?

```
[pool-1-thread-1] ERROR org.apache.kafka.connect.runtime.WorkerSinkTask - WorkerSinkTask{id=ElasticsearchSinkConnector-0} Offset commit failed, rewinding to last committed offsets
org.apache.kafka.connect.errors.ConnectException: Flush timeout expired with unflushed records: 2456
	at io.confluent.connect.elasticsearch.bulk.BulkProcessor.flush(BulkProcessor.java:302)
	at io.confluent.connect.elasticsearch.ElasticsearchWriter.flush(ElasticsearchWriter.java:217)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.flush(ElasticsearchSinkTask.java:125)
	at org.apache.kafka.connect.sink.SinkTask.preCommit(SinkTask.java:117)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.commitOffsets(WorkerSinkTask.java:299)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:165)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ewencp** [comment] 2017-07-24 19:21
Is there any other information in the log before this error? The message indicates that when the framework asked the connector to flush its data so the framework could commit offsets, the connector took too long to flush the data. The default timeout for this operation is 10s. You can try increasing this timeout with the `flush.timeout.ms` setting, but normally 10s should be plenty of time.

**Comment by panda87** [comment] 2017-07-24 20:22
I increased it to 60s with `flush.timeout.ms` and indeed it "solve" the issue.
But in the logs I still see 
```
[pool-1-thread-3] INFO org.apache.kafka.connect.runtime.WorkerSinkTask - WorkerSinkTask{id=ElasticsearchSinkConnector-0} Committing offsets
[pool-1-thread-3] WARN org.apache.kafka.connect.runtime.WorkerSinkTask - Commit of WorkerSinkTask{id=ElasticsearchSinkConnector-0} offsets timed out
[pool-1-thread-3] INFO org.apache.kafka.connect.runtime.WorkerSinkTask - WorkerSinkTask{id=ElasticsearchSinkConnector-0} Committing offsets
[pool-1-thread-3] WARN org.apache.kafka.connect.runtime.WorkerSinkTask - Commit of WorkerSinkTask{id=ElasticsearchSinkConnector-0} offsets timed out
```

But in the kafka-manager I can see the offsets increase (but not in the topic I created)
As you wrote, it's kind of odd that 10s is not enough to flush and update while my cluster doesn't work hard and the other management workers are getting data easily

**Comment by ewencp** [comment] 2017-07-24 21:25
@panda87 You are likely hitting https://issues.apache.org/jira/browse/KAFKA-4942, which is annoying but not actually an issue. This is fixed with Kafka 0.11.0.0.

**Comment by panda87** [comment] 2017-07-24 21:29
This can't be fixed also in kafka 0.10.2.* branch?
Or may I use kafka 0.11 with kafka connect while my kafka cluster is 0.10.2.1?
Is this possible to use different version for kafka-connect cluster and kafka cluster?

**Comment by ewencp** [comment] 2017-07-25 20:58
We generally only back port critical fixes (or minor stuff like documentation) to release branches. You can use 0.11 clients/connect/streams with a Kafka cluster on 0.10.2.1. See this blog post for more details: https://www.confluent.io/blog/upgrading-apache-kafka-clients-just-got-easier/

**Comment by panda87** [comment] 2017-07-25 21:13
Great!
Does the 3.2.2 plugin supports kafka 0.11?
Im also waiting for this patch that hopefully will be released soon [https://issues.apache.org/jira/browse/KAFKA-5567](https://issues.apache.org/jira/browse/KAFKA-5567)

Last thing, it's normal that instead of writing the offsets to the topic I set it's writing to __consumer_groups topic?

**Comment by ewencp** [comment] 2017-07-25 22:54
Yes, the 3.2.2 plugin will work with Kafka 0.11. As of Kafka 0.10.2, clients/connect/streams are protocol compatible both forwards and backwards. The only reason a Connect plugin wouldn't work with a newer/older version now is if it uses a feature that was added recently.

It is normal for sink connectors to write to `__consumer_groups`. Source connectors cannot do that because their offsets may not be structured like Kafka's and they don't have a consumer group to commit to, but sink connectors just reuse the functionality already provided by Kafka.

**Comment by panda87** [comment] 2017-07-26 08:37
Thanks for the very detailed answers @ewencp !!
My last concern right now is Connect visibility, how do I know how much processed, rejected, failed, time per bulk etc.

I will try to open jmx and see if Connect is supports some of these

**Comment by ewencp** [comment] 2017-07-26 18:13
@panda87 You can get metrics from the underlying consumer, see the metrics docs starting [here](http://kafka.apache.org/documentation.html#selector_monitoring) and [here](http://kafka.apache.org/documentation.html#new_consumer_monitoring). There aren't many connect-specific metrics, but we're looking at adding them in the next Kafka version.

**Comment by Tapppi** [comment] 2018-03-28 16:16
We are fairly certain that we are seeing the same root cause with our Elastic Cloud cluster. We get a slightly different "Read timed out" socket error that happens AFTER the task has already failed. There is no info anywhere about this error, but I theorise that elastic cloud's load handling just drops all sockets that have too much traffic, and thus we don't even get a sensible connect error. Maybe this could be improved to also print the original error. Apologies for the screenshot, we wen't ahead and deleted all instances of the task and I cannot get the error out otherwise ;)
![image](https://user-images.githubusercontent.com/3275280/38042228-7eb9643a-32bc-11e8-8471-b36753459788.png)

**Comment by kkitts** [comment] 2018-04-21 18:49
I am running into this same error loading data into Elasticsearch. Is there any update on this? Is it fixed in the Confluent 4.1 release?

**Comment by kkitts** [comment] 2018-04-23 18:15
Actually, I read a similar recommendation in another post. I set the following parameters:

Batch.size = 100
max.buffered.records = 1000
Max.retries = 10
Retry.backoff.ms = 1000
flush.timeout.ms = 10000
max.in.flight.requests = 3

After making the changes above everything works. Of course, the throughput is somewhat reduced - but no records are lost and all 40 million rows of my data set loads without problem.

I’ve actually discovered that I only set 1 endpoint in the connection url (although I have a 12 node Elasticsearch cluster). I am going to increase the number of endpoints in connect.url and see if I can increase the throughput.

**Comment by NathanNam** [comment] 2019-06-13 22:57
@panda87 @kkitts @Tapppi Do you still face this issue?

**Comment by deepakagg** [comment] 2019-08-29 20:49
I am facing this issue and the throughout with elasticsearch is very low

**Comment by foxyriver** [comment] 2019-10-17 08:10
try to increase the heap size of Elasticsearch

**Comment by levzem** [comment] 2020-01-09 23:11
above solutions are correct - thus closing

**Closed by levzem** 2020-01-09 23:11 UTC

**Comment by udbhav** [comment] 2020-09-16 23:13
This might be helpful to somebody else who runs into this issue, but I discovered that I kept triggering this issue because I was querying ES during my testing to see if the sync was working, which would then trigger ES's refresh interval behavior as outlined here: https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-indexing-speed.html

If you anticipate read queries happening while you're streaming from the connector, you could also try unsetting or increasing the refresh interval.
