### ISSUE TITLE
ES Connector Schema Registry 401 Unauthorized

### ISSUE THREAD

**Issue by JustinMoser** [confluentinc/kafka-connect-elasticsearch#343] opened 2019-10-04 15:21 UTC
Hi,
I am a Confluent Cloud user and have setup the ES connector (deployed on EC2), with the following config:

```
{
	"name": "elasticsearch-sink",
	"connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
	"connection.url": "ES_URL",
	"connection.username": "ES_USERNAME",
	"connection.password": "ES_PASSWORD",
	"topics": "new-paper-raw",
	"type.name": "_doc",
	"auto.create.indices.at.start": "false",
	"key.ignore": "false",
	"errors.log.enable": "true",
	"schema.registry.url": "SCHEMA_REGISTRY_URL",
	"key.converter": "io.confluent.connect.avro.AvroConverter",
	"key.converter.schema.registry.url": "SCHEMA_REGISTRY_URL",
	"value.converter": "io.confluent.connect.avro.AvroConverter",
	"value.converter.schema.registry.url": "SCHEMA_REGISTRY_URL",
	"basic.auth.credentials.source": "USER_INFO",
	"basic.auth.user.info": "SCHEMA_REGISTRY_API_KEY:SCHEMA_REGISTRY_API_SECRET"
}
```

I have used the Schema Registry auth details generated in Confluent Cloud, and set them in my connector config above, as instructed here:

https://docs.confluent.io/current/schema-registry/connect.html

However, a few seconds after connector creation, using the endpoint:

`KAFKA_CONNECT_SERVER/connectors/elasticsearch-sink/status`

I get the response:

```
{
    "name": "elasticsearch-sink",
    "connector": {
        "state": "RUNNING",
        "worker_id": "10.0.1.137:8083"
    },
    "tasks": [{
        "id": 0,
        "state": "FAILED",
        "worker_id": "10.0.1.137:8083",
        "trace": "org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
             org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
             org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
             org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:484)
             org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)
             org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:320)
             org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
             org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
             org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
             org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
             java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
             java.util.concurrent.FutureTask.run(FutureTask.java:266)
             java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             java.lang.Thread.run(Thread.java:748)
             Caused by: org.apache.kafka.connect.errors.DataException: Failed to deserialize data for topic new-paper-raw to Avro: 
             io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:107)
             org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$0(WorkerSinkTask.java:484)
             org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
             org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162) ... 13 more
             Caused by: org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id 100017
             Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Unauthorized; error code: 401
             io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:226)
             io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:252)
             io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:482)
             io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:475)
             io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaByIdFromRegistry(CachedSchemaRegistryClient.java:151)
             io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getBySubjectAndId(CachedSchemaRegistryClient.java:230)
             io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getById(CachedSchemaRegistryClient.java:209)
             io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:116)
             io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:215)
             io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:145)
             io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:90)
             org.apache.kafka.connect.runtime.WorkerSinkTask.lambda$convertAndTransformRecord$0(WorkerSinkTask.java:484)
             org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
             org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
             org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
             org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:484)
             org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)
             org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:320)
             org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
             org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
             org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
             org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
             java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
             java.util.concurrent.FutureTask.run(FutureTask.java:266)
             java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             java.lang.Thread.run(Thread.java:748)"
    }],
    "type": "sink"
}
```

The important part:

```
Error retrieving Avro schema for id 100017
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Unauthorized; error code: 401
```

100017 is the ID of the key schema in Schema Registry, so it is at least getting that detail successfully, but it seems to fail when getting the actual schema for that ID.

I have looked at the source code for the relevant class from the stack-trace:

https://github.com/confluentinc/schema-registry/blob/master/client/src/main/java/io/confluent/kafka/schemaregistry/client/rest/RestService.java#L553

and by looking at the method `getId`, I have manually constructed the request URL it constructs on the line:

`String path = String.format("/schemas/ids/%d?fetchMaxId=%b", id, fetchMaxId);`

and then making a request in Postman to:

`SCHEMA_REGISTRY_URL/schemas/ids/100017`

with the same auth details specified in the connector config, and I get a 200 response:

```
{"schema":"{\"type\":\"record\",\"name\":\"paper_new_raw_key\",\"namespace\":\"com.REDACTED.paper.new.raw\",\"fields\":[{\"name\":\"uuid\",\"type\":\"string\"},{\"name\":\"created_at\",\"type\":\"long\"}]}"}
```

However, the difference is that Postman creates a base64 encoded version of the basic_auth details (equivalent to `curl -u SCHEMA_REGISTRY_API_KEY:SCHEMA_REGISTRY_API_SECRET SCHEMA_REGISTRY_URL`) and therefore that is what the Schema Registry API expects.

So, am I doing something wrong in the connector configuration? Or is there a problem with the connector not passing the correct auth details (with base64 encoding) from the config to the schema registry request?

**Comment by terryf82** [comment] 2019-11-07 05:14
Experiencing the same issue using the Debezium connector, when it tries to create a schema as part of the initial snapshot.

Common thread is the Confluent Cloud Schema Registry, it seems like it doesn't interface cleanly with the way Kafka Connect provides the credentials. I'll lodge a support ticket with Confluent Cloud and let you know when I hear anything back.

**Comment by cricket007** [comment] 2019-11-28 07:12
Note: this issue should be moved to the schema registry repo because the issue is with the AvroConverter properties, not Elastic connector 

Not tested, but replace all your registry configs with something like this (prefix the auth with the appropriate converter) 

```
	"value.converter": "io.confluent.connect.avro.AvroConverter",
	"value.converter.schema.registry.url": "SCHEMA_REGISTRY_URL",
	"value.converter.basic.auth.credentials.source": "USER_INFO",
	"value.converter.basic.auth.user.info": "
```

Repeat for the key converter

**Comment by ajit-mote** [comment] 2019-12-21 18:55
above is correct

**Comment by ajit-mote** [comment] 2019-12-21 18:56
Yes this is work fine i tested thanks Jordan.

**Comment by levzem** [comment] 2020-02-08 00:07
Closing because this is resolved and an SR issue, thanks for the help @cricket007

**Closed by levzem** 2020-02-08 00:07 UTC
