### ISSUE TITLE
Error: java.lang.NoClassDefFoundError: io/searchbox/action/Action

### ISSUE THREAD

**Issue by Ziauddin135** [confluentinc/kafka-connect-elasticsearch#366] opened 2019-12-11 09:44 UTC
![connector_error](https://user-images.githubusercontent.com/25635087/70609626-213ae980-1c28-11ea-8696-7864ea591b0a.JPG)

Hi All,

I am trying to run **confluentinc/kafka-connect-elasticsearch:5.3.0**  in my local connect distribute worker. with following config. i am getting error attached  and also provided at the bottom. kindly help to understand how can i resolve this issue and run elastic search connector.

```
{
  "name": "elasticsearch-sink",
  "config": {
    "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
    "tasks.max": "1",
    "topics": "es_test",
    "key.ignore": "false",
    "connection.url": "http://localhost:9200",
    "type.name": "mytype",
    "name": "elasticsearch-sink",
    "topic.index.map": "es_test:myindex"
  },
  "tasks": [],
  "type": null
}  
```
 **Error**
java.lang.NoClassDefFoundError: io/searchbox/action/Action
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:123)
        at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:51)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:301)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.searchbox.action.Action
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 11 more
[2019-12-11 15:03:29,458] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)

**Comment by MicDeDuiwel** [comment] 2019-12-19 11:28
I am experiencing the exact same issue. Trying to create a kafka-connect kubernetes deployment using strimzi, I package kafka-connect as a plugin. I thought that it might be a case of the jar file not including all the dependencies, but when I edit my pom.xml file to include the follwing descriptor:
`                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
`

I get a different error message:
> ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-elasticsearch-sink-0]
org.apache.kafka.connect.errors.ConnectException: Couldn't start ElasticsearchSinkTask due to connection error:
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:146)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:133)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:122)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:51)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:300)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:396)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:355)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:359)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:381)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at io.searchbox.client.http.JestHttpClient.executeRequest(JestHttpClient.java:133)
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:70)
	at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:63)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.getServerVersion(JestElasticsearchClient.java:227)
	at io.confluent.connect.elasticsearch.jest.JestElasticsearchClient.<init>(JestElasticsearchClient.java:142)
	... 12 more
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
	... 35 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 41 more



This is my original error message (same as OP):

> ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-elasticsearch-sink-0]
java.lang.NoClassDefFoundError: io/searchbox/action/Action
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:122)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:51)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:300)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:189)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:177)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:227)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.searchbox.action.Action
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:104)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 11 more

**Comment by levzem** [comment] 2019-12-19 23:56
@Ziauddin135

it is hard for me to comment on the exact solution to your issue without knowing more details. I don't know how you are running the connector (through confluent platform or otherwise). I can say that that error message is very typical for when a dependency is missing (or is in conflict with an older version). Most likely you are just missing some of the dependency jars. @MicDeDuiwel's fix looks promising. 

@MicDeDuiwel 
I don't know what your configurations are, but if you are using SSL configs, you might have misconfigured them somehow and the connector is having trouble authenticating.

**Comment by MicDeDuiwel** [comment] 2019-12-20 10:28
Thanks for the feedback @levzem. I don't know if this helps narrow down the issues, but I use the following configuration for my elasticsearch sink connector:


    "name": "elasticsearch-sink",
    "config": {
        "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
        "tasks.max": "1",
        "topics": "testsink",
	"topic.index.map": "testsink:elasticsink",
        "connection.url": "https://elasticsearch-sample-es-http.elastic-system.svc:9200",
        "schema.ignore": "true",
	"key.ignore": "true",
        "type.name": "kafka-connect",
	"connection.username": "elastic",
	"connection.password": "..."
    }

**Comment by levzem** [comment] 2019-12-20 21:14
@MicDeDuiwel 

looks like you are connecting over `HTTPS`. Please see the [documentation](https://docs.confluent.io/current/connect/kafka-connect-elasticsearch/configuration_options.html#security) on how to correctly configure the connector to connect over `HTTPS`. 

and here is more on the [exception](https://stackoverflow.com/questions/9619030/resolving-javax-net-ssl-sslhandshakeexception-sun-security-validator-validatore).

**Comment by Ziauddin135** [comment] 2019-12-21 04:44
> Thanks for the feedback @levzem. I don't know if this helps narrow down the issues, but I use the following configuration for my elasticsearch sink connector:
> 
> ```
> "name": "elasticsearch-sink",
> "config": {
>     "connector.class": "io.confluent.connect.elasticsearch.ElasticsearchSinkConnector",
>     "tasks.max": "1",
>     "topics": "testsink",
> "topic.index.map": "testsink:elasticsink",
>     "connection.url": "https://elasticsearch-sample-es-http.elastic-system.svc:9200",
>     "schema.ignore": "true",
> "key.ignore": "true",
>     "type.name": "kafka-connect",
> "connection.username": "elastic",
> "connection.password": "..."
> }
> ```

Hi @MicDeDuiwel , 

It looks you are providing plugin path other than the kafka lib. Please cut and paste jest jars, common utils jar in the kafka\lib from your plugins directory. And try

**Comment by cricket007** [comment] 2020-01-07 02:06
Please show your entire docker run command or compose file

**Comment by levzem** [comment] 2020-01-25 21:06
closing due to no response - please feel free to reopen if you still need help

**Closed by levzem** 2020-01-25 21:06 UTC
Labels: help wanted

**Comment by patsadow2** [comment] 2020-01-27 19:08
I don't use http and i have the same problem, yesterday it was working and today it doen't i don't kwno why ? Windows sucks ? Docker sucks ? I don't have any latest version of docker images.


at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:122)

**Comment by xyfigo** [comment] 2020-03-07 18:31
> I don't use http and i have the same problem, yesterday it was working and today it doen't i don't kwno why ? Windows sucks ? Docker sucks ? I don't have any latest version of docker images.
> 
> at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:122)
> 
> https://github.com/debezium/debezium-examples/tree/master/unwrap-smt
> 
> elastic + mysql

I have the same issue when running the debezium unwrap-smt example. Do you solve the problem?

**Comment by tirelibirefe** [comment] 2020-05-26 13:19
is there anyone who could get a workaround?
I''ve a similar problem.

[https://stackoverflow.com/questions/62015340/elasticsearch-connector-doesnt-work-java-lang-noclassdeffounderror-com-googl](https://stackoverflow.com/questions/62015340/elasticsearch-connector-doesnt-work-java-lang-noclassdeffounderror-com-googl)

**Comment by chenpengxiang** [comment] 2020-09-19 11:48
I had the same issue.  After copy the all the share libs under target/kafka-connect-elasticsearch-6.1.0-SNAPSHOT-development/share/java/kafka-connect-elasticsearch/**  and guava-28.1-jre.jar (jest-6.3.1.jar depends on it) to kafka/libs, then it works. 
![Uploading Screen Shot 2020-09-19 at 7.42.53 PM.png…]()
