### ISSUE TITLE
Enable string fields for aggregation in Elasticsearch even if schema.ignore=false

### ISSUE THREAD

**Issue by rmoff** [confluentinc/kafka-connect-elasticsearch#211] opened 2018-05-18 15:08 UTC
When loading data to Elasticsearch for analytics, usually it is desirable to be able to perform analysis on complete string fields in Elasticsearch. [This behaviour changed in recent versions of Elasticsearch](https://www.elastic.co/blog/strings-are-dead-long-live-strings). The example Elasticsearch use is in the case of city, you want to look at data based on "New York" (non-analysed) vs "New" and "York" (analysed).

In order to be able to aggregate fields by their complete value in Elasticsearch 6, they should have a `type` of `keyword`.  

If `schema.ignore=true` in the Elasticsearch connector config then string fields are created as would be desired: 

```
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
```

Alternatively, if `schema.ignore=true` and a dynamic mapping is provided, for example: 

    curl -XPUT "http://localhost:9200/_template/kafkaconnect/" -H 'Content-Type: application/json' -d'{"index_patterns":"*","settings":{"number_of_shards":1,"number_of_replicas":0},"mappings":{"_default_":{"dynamic_templates":[{"dates":{"match":"EXTRACT_TS","mapping":{"type":"date"}}},{"non_analysed_string_template":{"match":"*","match_mapping_type":"string","mapping":{"type":"keyword"}}}]}}}'

Then resulting field may look something like 

            "type": "keyword"

So long as the field is `type=keyword` (or has a nested field of `keyword`) it can be used for aggregation: 

![image](https://user-images.githubusercontent.com/3671582/40242373-6719c45c-5ab5-11e8-8299-6d43ba48a3d7.png)

_However_, if `schema.ignore=false` (i.e. utilise the schema of the source Connect records) then the created fields are 

            "type": "text"

**Regardless of whether a dynamic mapping template is used or not**. This means that the field will not be available for aggregation

![image](https://user-images.githubusercontent.com/3671582/40242310-3d78a690-5ab5-11e8-81a0-08064e872478.png)

==> When Kafka Connect is creating the target mapping based on the source schema (`schema.ignore=false`) can it adhere to the [suggested default behaviour in this blog from Elastic](https://www.elastic.co/blog/strings-are-dead-long-live-strings) and map strings as both text _and_ keyword?

**Comment by rhauch** [comment] 2018-05-18 15:26
@rmoff that appears to be a [recent change](https://github.com/confluentinc/kafka-connect-elasticsearch/pull/169) to support ES 6, and [this is the code](https://github.com/confluentinc/kafka-connect-elasticsearch/blob/361bd4d22a63a526e31164f0052f6737c350ce65/src/main/java/io/confluent/connect/elasticsearch/Mapping.java#L133-L142) that is explicitly setting the `text` type for the mapping.

We could change that to `keyword`, but is that backward compatible? The [aforementioned blog post](https://www.elastic.co/blog/strings-are-dead-long-live-strings) seems to suggest, though, that `text` is analyzed but `keyword` is not. If that is the case, then changing this would seem to imply it is not backward compatible; that `keyword` is not a superset of the functionality defined by `text`.

cc @rayokota

**Comment by rhauch** [comment] 2018-05-18 15:31
I think the problem is that the [default behavior](https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-intro.html) of the `index` property was to be analyzed, and I think that's why the PR used `text` by default.

**Comment by rmoff** [comment] 2018-05-21 08:44
(I've edited the title & initial comment, as I mis-used the "analysed" terminology).

How about changing the behaviour to map both `text` and `keyword`? Per the blog

```
{
  "foo": {
    "type" "text",
    "fields": {
      "keyword": {
        "type": "keyword",
        "ignore_above": 256
      }
    }
  }
}
```

This would then be backward compatible (still mapped as a `text` field) but then also enable the non-analysed/aggregation capabilities by default too. This would also mimic the default (and thus user-expected) behaviour for strings in Elasticsearch. 

What do you think?

**Comment by rayokota** [comment] 2018-05-21 16:36
@rmoff , that's exactly what's proposed in #188

**Comment by rmoff** [comment] 2018-05-21 20:49
@rayokota so…can we do it? :) It would make a big impact in the usability of this connector.

**Comment by rayokota** [comment] 2018-05-22 16:47
Yes, I'll try to get this in for 5.0

**Comment by rayokota** [comment] 2018-05-30 23:30
Fixed by https://github.com/confluentinc/kafka-connect-elasticsearch/pull/216

**Closed** 2018-05-30 23:30 UTC
