### ISSUE TITLE
Created 2 indices when using transform to convert topic

### ISSUE THREAD

**Issue by gp0014** [confluentinc/kafka-connect-elasticsearch#296] opened 2019-04-01 04:21 UTC
I am using TimestampRouter to convert the topic, since I need to sort the messages by day. 
- The original topic is "mysql.core.table1".
- The transform is configured like this
- The date is 2019-04-01
```
{
    ......
    "transforms": "topic",
    "transforms.topic.type": "org.apache.kafka.connect.transforms.TimestampRouter",
    "transforms.topic.timestamp.format": "yyyyMMdd",
    "transforms.topic.topic.format": "${topic}.${timestamp}",
    ......
}
```
#### Expected result
ES-Sink will create an index named "mysql.core.table1.20190401" in ES.

#### Actual result
ES-Sink creates 2 indices named "mysql.core.table1.20190401" and "mysql.core.table1" in ES, and puts the docs into "mysql.core.table1.20190401" index.

**Comment by babadofar** [comment] 2019-04-04 06:38
Thanks for the example code, I need it :)
If the changelog is correct, this is fixed in version 5.20 
https://docs.confluent.io/5.2.0/connect/kafka-connect-elasticsearch/changelog.html#version-5-2-0
https://github.com/confluentinc/kafka-connect-elasticsearch/pull/275

**Comment by jpeyper** [comment] 2019-04-23 22:05
I am running version 5.2.1 and am experiencing the same issue with the `RegexRouter`.

I'll try to get a minimum example going soon.

**Comment by jpeyper** [comment] 2019-04-28 12:10
I did a bit of digging in the PR #275 and found that you need to set this in config for it to behave as the OP (and myself) expected.

```
"auto.create.indices.at.start": "false",
```

It seems to be missing from the config docs (https://docs.confluent.io/current/connect/kafka-connect-elasticsearch/configuration_options.html), but it does work for me on 5.2.1.

**Comment by levzem** [comment] 2019-11-19 18:00
@babadofar, @jpeyper you are entirely correct. The issue is because the default is set to `true` for that config. The latest docs area updated to reflect this config. 

I will close this now, but if you have any questions feel free to re-open.

**Closed by levzem** 2019-11-19 18:00 UTC
