### ISSUE TITLE
[KafkaConnect to ES ]org.apache.kafka.connect.errors.DataException: STRUCT is not supported as the document id.

### ISSUE THREAD

**Issue by JanardhanVarikuti** [confluentinc/kafka-connect-elasticsearch#193] opened 2018-04-07 22:07 UTC
Hi,

Getting the below error while trying to connect to Elastic Search (dokcer image - elasticsearch:2.4.3) using Confluent Kafka connect (v4.0)

===================================================================
[2018-04-07 17:12:51,083] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:515)
org.apache.kafka.connect.errors.DataException: STRUCT is not supported as the document id.
	at io.confluent.connect.elasticsearch.DataConverter.convertKey(DataConverter.java:88)
	at io.confluent.connect.elasticsearch.DataConverter.convertRecord(DataConverter.java:105)
	at io.confluent.connect.elasticsearch.ElasticsearchWriter.tryGetIndexableRecord(ElasticsearchWriter.java:254)
	at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:232)
	at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:159)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

===================================================================

 > I'm running the kafka connect in standalone mode with the following command :

       ./bin/connect-standalone etc/schema-registry/connect-avro-standalone.properties etc/kafka-connect-elasticsearch/elasticsearch_testTopic_distributed.properties 
	   
 > My elasticsearch_testTopic_distributed.properties details are given below :
 
			name=elasticsearch-sink
			connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
			tasks.max=1
			topics=test123
			key.ignore=false
			connection.url=http://localhost:9200
			type.name=kafka-connect-test
			topic.index.map=test123:test123

 > And my data present in the topic "test123" is of Avro format and something like this :
 
							{
								"KEY_NUMBER": "ABC87764448"	
							}
							{
								"record001": {
									"com.hello.record001": {
										
										"PARAMETER1": {
											"string": "90"
										},
										"PARAMETER2": {
											"string": "AJ"
										},
										"record0011": {
											"array": [{
												"NAME1": {
													"string": "ANN"
												},
												"NAME2": {
													"string": "PLM"
												}
											},
											{
												"NAME1": {
													"string": "ANN11"
												},
												"NAME2": {
													"string": "PLM22"
												}
											},				
											]
										},
										"record0012": null,			
										"record0013": {
											"com.hello.record0013": {
												"NAME2": {
													"string": "Hello"
												}
											}
										},
										"record0013": {
											"array": [{
												"NAME1": {
													"string": "Hello"
												},
												"NAME2": {
													"string": "POLP"
												},
												
												"record001112": {
													"array": [{
														"NAME": {
															"string": "HJ"
														},
														"FIRST": {
															"string": "M"
														}
													}
													]
												},					
												
												]
												}
											}]
										},
										"RECORD002": {
											"com.hello.RECORD002": {
												"DAY": {
													"string": "  "
												},
												"WORK": {
													"string": "OKII"
												}
											}
										}
										
									}
								}
							}

Any help is greatly appreciated!!

**Comment by JanardhanVarikuti** [comment] 2018-04-10 00:10
Hi @rhauch , thanks for your reply. After applying SMT,  getting another error. Please find the properties that I'm using =

                     name=elasticsearch-test8-sink
                     connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
                      tasks.max=1
                      topics=testtopic87
                       key.ignore=false
                       connection.url=http://localhost:9200
                      type.name=kafka-connect-test8
                      transforms=extract
                      transforms.createKey.type=org.apache.kafka.connect.transforms.ValueToKey
                      transforms.createKey.fields=KEY_NUMBER
                      transforms.extract.type=org.apache.kafka.connect.transforms.ExtractField$Key
                       transforms.extract.field=KEY_NUMBER

Error message --------

`Janardhan [2 hours ago]
[2018-04-09 18:21:25,965] ERROR WorkerSinkTask{id=elasticsearch-test8-sink-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. (org.apache.kafka.connect.runtime.WorkerSinkTask:515)
java.lang.NullPointerException
    at io.confluent.connect.elasticsearch.DataConverter.preProcessStructValue(DataConverter.java:305)
    at io.confluent.connect.elasticsearch.DataConverter.preProcessValue(DataConverter.java:233)
    at io.confluent.connect.elasticsearch.DataConverter.preProcessStructValue(DataConverter.java:305)
    at io.confluent.connect.elasticsearch.DataConverter.preProcessValue(DataConverter.java:233)
    at io.confluent.connect.elasticsearch.DataConverter.preProcessStructValue(DataConverter.java:305)
    at io.confluent.connect.elasticsearch.DataConverter.preProcessValue(DataConverter.java:233)
    at io.confluent.connect.elasticsearch.DataConverter.convertRecord(DataConverter.java:112)
    at io.confluent.connect.elasticsearch.ElasticsearchWriter.tryGetIndexableRecord(ElasticsearchWriter.java:254)
    at io.confluent.connect.elasticsearch.ElasticsearchWriter.write(ElasticsearchWriter.java:232)
    at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.put(ElasticsearchSinkTask.java:159)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:495)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
)
[2018-04-09 18:21:25,967] ERROR WorkerSinkTask{id=elasticsearch-test8-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
    at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:517)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:288)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
    at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)

Caused by: java.lang.NullPointerException
    at io.confluent.connect.elasticsearch.DataConverter.preProcessStructValue(DataConverter.java:305)
    at io.confluent.connect.elasticsearch.DataConverter.preProcessValue(DataConverter.java:233)
    at io.confluent.connect.elasticsearch.DataConverter.preProcessStructValue(DataConverter.java:305)
    at io.confluent.connect.elasticsearch.DataConverter.preProcessValue(DataConverter.java:233)
    at io.confluent.connect.elasticsearch.DataConverter.preProcessStructValue(DataConverter.java:305)

    ... 10 more
[2018-04-09 18:21:25,968] ERROR WorkerSinkTask{id=elasticsearch-test8-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:173)
[2018-04-09 18:21:25,968] INFO Stopping ElasticsearchSinkTask. (io.confluent.connect.elasticsearch.ElasticsearchSinkTask:175)`

**Comment by rhauch** [comment] 2018-04-10 02:04
@JanardhanVarikuti, the key is no longer a problem, so now I think you're onto a different issue, and that sounds like it may be similar to #192, though in your case I think the exception is caused by an optional field of type Struct with is a null value (e.g., the `record0012` field, so might this field be optional and of type struct?).

I'd suggest trying to build the latest off of the `4.0.x` branch (or the `master`) depending upon the version you're already using.

**Comment by JanardhanVarikuti** [comment] 2018-04-10 02:31
@rhauch Thanks for the details. Currently I'm using **confluent-4.0.0**.  So you want me to clone the code of the _https://github.com/confluentinc/kafka-connect-elasticsearch_ and build the code? 

If yes, could you please provide me the steps for building the repository?

Thanks

**Comment by JanardhanVarikuti** [comment] 2018-04-10 19:56
@rhauch Could you please provide me/suggest the steps to build the _kafka-connect-elasticsearch_ ? As I've tried so far -
 1> cloned the kafka-connect-elasticsearch (https://github.com/confluentinc/kafka-connect-elasticsearch.git)
2> Tried building by using "mvn package"
  but getting below error - 
           Non-resolvable parent POM for io.confluent:kafka-connect-elasticsearch:[unknown-version]: 
           Failure to find io.confluent:common:pom:5.0.0-SNAPSHOT in 
           http://packages.confluent.io/maven/ was cached in the local repository, resolution will not be 
            reattempted until the update interval of confluent has elapsed or updates are forced and 
           'parent.relativePath' points at wrong local POM @ line 7, column 13
         @

Please suggest 
Thanks!

**Comment by C0urante** [comment] 2018-04-11 00:25
Hi @JanardhanVarikuti, thanks for your email. It looks like you need to download and locally install Confluent's common artifact first:

```bash
$ git clone https://github.com/confluentinc/common.git
$ cd common
$ mvn install
```

**Comment by JanardhanVarikuti** [comment] 2018-04-11 01:06
Hi @C0urante , Thanks for your reply.

I've tried to do the "mvn install" and got the below error:

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] assembly-plugin-boilerplate ........................ SUCCESS [ 20.544 s]
[INFO] Build Tools ........................................ SUCCESS [  7.444 s]
[INFO] common ............................................. SUCCESS [01:16 min]
[INFO] utils .............................................. SUCCESS [  7.891 s]
[INFO] metrics ............................................ SUCCESS [  9.216 s]
[INFO] config ............................................. SUCCESS [  2.417 s]
[INFO] package ............................................ SUCCESS [ 14.596 s]
**[INFO] utility-belt ....................................... FAILURE [01:13 min]**
[INFO] cp-base ............................................ SKIPPED
[INFO] Common ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] **BUILD FAILURE**
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:32 min
[INFO] Finished at: 2018-04-10T21:01:23-04:00
[INFO] Final Memory: 44M/475M
[INFO] ------------------------------------------------------------------------
**[ERROR] Failed to execute goal on project utility-belt**: Could not resolve dependencies for project io.confluent:utility-belt:jar:5.0.0-SNAPSHOT: The following artifacts could not be resolved: org.apache.kafka:kafka_2.11:jar:1.2.0-SNAPSHOT, org.apache.kafka:kafka-clients:jar:1.2.0-SNAPSHOT, org.apache.kafka:kafka-clients:jar:test:1.2.0-SNAPSHOT, org.apache.kafka:kafka_2.11:jar:test:1.2.0-SNAPSHOT: Could not find artifact org.apache.kafka:kafka_2.11:jar:1.2.0-SNAPSHOT in confluent (http://packages.confluent.io/maven/) -> [Help 1]
[ERROR] 

Let me know if I'm missing anything.
Thanks for your help.

**Comment by C0urante** [comment] 2018-04-11 15:51
@JanardhanVarikuti, it looks like you need to do the same thing with Apache Kafka. Notice how the dependencies that couldn't be located have the version `1.2.0-SNAPSHOT`; in the case of Kafka and some Confluent projects, this means that the project needs to be downloaded and then installed locally since it hasn't been released into an external repository yet.

In the case of Kafka, you should clone the repository:
```bash
$ git clone https://github.com/apache/kafka
```
and then install the current snapshot version of Kafka locally by following the instructions for [downloading and installing the Gradle wrapper](https://github.com/apache/kafka#first-bootstrap-and-download-the-wrapper) and then [installing the snapshot version locally](https://github.com/apache/kafka#installing-the-jars-to-the-local-maven-repository). As is pointed out in the README for Kafka, make sure you have Gradle 3.0+ installed (I tried building with Gradle 2.10 and encountered build failures).

**Comment by JanardhanVarikuti** [comment] 2018-04-11 18:54
Hi @C0urante ,  Yes after building the following, an elastic search connector jar(_kafka-connect-elasticsearch-5.0.0-SNAPSHOT.jar_) has been created.

1> Cloned the kafka and build using Grade 3.0+ (gradle wrapper,gradle installAll)
2> Cloned the common and build using maven
3> Cloned the confluent/elastic search and build using maven

But when running the elastic search connector, the same is running fine with the following properties, but when it getting displayed on ES (using Dejavu as a UI), I'm not seeing the KEY.

                 name=elasticsearch-test9-sink
                 connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
                  tasks.max=1
                  topics=testtopic87
                   key.ignore=true
                   connection.url=http://localhost:9200
                  type.name=kafka-connect-test9
                  transforms=extract
                  transforms.createKey.type=org.apache.kafka.connect.transforms.ValueToKey
                  transforms.createKey.fields=KEY_NUMBER
                  transforms.extract.type=org.apache.kafka.connect.transforms.ExtractField$Key
                   transforms.extract.field=KEY_NUMBER

screenshot is below: (no Key (KEY_NUMBER) is getting displayed )
![image](https://user-images.githubusercontent.com/7712148/38636908-99550ade-3d97-11e8-804d-475d8fa459fa.png)

--------------

When I try with the below property , getting NPE:
                 name=elasticsearch-test9-sink
                 connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
                  tasks.max=1
                  topics=testtopic87
                   key.ignore=true
                   connection.url=http://localhost:9200
                  type.name=kafka-connect-test9
                  transforms=createKey,extract
                  transforms.createKey.type=org.apache.kafka.connect.transforms.ValueToKey
                  transforms.createKey.fields=KEY_NUMBER
                  transforms.extract.type=org.apache.kafka.connect.transforms.ExtractField$Key
                   transforms.extract.field=KEY_NUMBER

NPE error:

	java.lang.NullPointerException
	at org.apache.kafka.connect.transforms.ValueToKey.**applyWithSchema**(**ValueToKey.java**:85)
	at org.apache.kafka.connect.transforms.ValueToKey.apply(ValueToKey.java:65)
	at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:38)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:287)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


Any idea?
Thanks

**Comment by C0urante** [comment] 2018-04-12 21:43
@JanardhanVarikuti--you have `key.ignore=true` in your configuration file; according to Confluent's [Elasticsearch connector docs](https://docs.confluent.io/current/connect/connect-elasticsearch/docs/configuration_options.html#data-conversion):

> When [`key.ignore`] is set to `true`, document IDs will be generated as the record’s `topic+partition+offset`.

Try setting it to `false` (or omitting it entirely, as `false` is the default) and see what happens.

**Comment by JanardhanVarikuti** [comment] 2018-04-13 01:28
@C0urante will try and let you know. Thanks

**Comment by JanardhanVarikuti** [comment] 2018-04-17 03:30
HI @C0urante , I've tired without **key.ignore**, but this time got NPE:

**ES properties:**
_name=elasticsearch-test15-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topics=test_topic
connection.url=http://localhost:9200
type.name=kafka-connect-test15
transforms=createKey
transforms.createKey.type=org.apache.kafka.connect.transforms.ValueToKey
transforms.createKey.fields=KEY_NUMBER_


**NPE**

[2018-04-16 21:38:12,867] ERROR WorkerSinkTask{id=elasticsearch-test15-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
java.lang.NullPointerException
	at org.apache.kafka.connect.transforms.ValueToKey.applyWithSchema(ValueToKey.java:85)
	at org.apache.kafka.connect.transforms.ValueToKey.apply(ValueToKey.java:65)
	at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:38)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:287)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:198)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:166)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-04-16 21:38:12,876] ERROR WorkerSinkTask{id=elasticsearch-test15-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:173)
[2018-04-16 21:38:12,876] INFO Stopping ElasticsearchSinkTask. (io.confluent.connect.elasticsearch.ElasticsearchSinkTask:178)

**Comment by C0urante** [comment] 2018-04-17 17:48
@JanardhanVarikuti Have you tried only using the `extract` transform, instead of the `createKey` transform?

**Comment by JanardhanVarikuti** [comment] 2018-04-17 20:03
@C0urante yes I've tried using the `extract` transform and ended up in the scenario where I've explained (screenshot is below: (no Key (KEY_NUMBER) is getting displayed ))  above.

![image](https://user-images.githubusercontent.com/7712148/38893540-93b1f50e-4258-11e8-9c5a-80dc2ca021b0.png)


I've used below properties:
```
name=elasticsearch-test15-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topics=test_topic
connection.url=http://localhost:9200
type.name=kafka-connect-test15
transforms=extract
transforms.extract.type=org.apache.kafka.connect.transforms.ExtractField$Key
transforms.extract.field=KEY_NUMBER
```
Thanks for the help @C0urante

**Comment by ArpitaSheelavant** [comment] 2018-08-25 14:06
When I am running the below command ,I am getting NoClassDefFoundError

bin/windows/connect-standalone.bat config/connect-standalone.properties config/connect-file-sink
-1.properties

ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
java.lang.NoClassDefFoundError: io/searchbox/action/Action
at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:120)
at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.start(ElasticsearchSinkTask.java:51)
at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:281)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:170)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.searchbox.action.Action
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 11 more

My config property file,
name=elasticsearch-sink
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topics=elasticsearch-test
connection.url=http://localhost:9200
type.name=kafka-connect
key.ignore=true

**Comment by rmoff** [comment] 2019-04-25 10:44
To close out this ticket for the original issue (`STRUCT is not supported as the document id`): use the [`ExtractField` SMT](https://docs.confluent.io/current/connect/transforms/extractfield.html#extractfield), for example: 

```
        "transforms": "extractKey",
        "transforms.extractKey.type":"org.apache.kafka.connect.transforms.ExtractField$Key",
        "transforms.extractKey.field":"id"
```

**Closed by rmoff** 2019-04-25 10:45 UTC
Labels: question

**Comment by deuscapturus** [comment] 2021-07-15 15:19
The `ExtractField` SMT is a solution only when the key has a single field.
