### ISSUE TITLE
Schema Registry - Schema not found; error code: 40403

### ISSUE THREAD

**Issue by zoltan-fedor** [confluentinc/kafka-connect-elasticsearch#59] opened 2016-12-21 21:42 UTC
I am trying to run the ES connector against an Avro-based Kafka topic, which is using the Schema Registry.
Unfortunately when the connector starts it fails fetching the schema from the Schema Registry.

**error:**
```
[2016-12-21 21:30:51,955] ERROR Task ES-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
org.apache.kafka.connect.errors.DataException: Failed to deserialize data to Avro: 
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:109)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:358)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:239)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id 421
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema not found; error code: 40403
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:170)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:187)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:323)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:316)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaByIdFromRegistry(CachedSchemaRegistryClient.java:63)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getBySubjectAndID(CachedSchemaRegistryClient.java:118)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:121)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:190)
	at io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:130)
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:99)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:358)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:239)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-21 21:30:51,961] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:143)
[2016-12-21 21:30:51,961] INFO Stopping ElasticsearchSinkTask. (io.confluent.connect.elasticsearch.ElasticsearchSinkTask:135)
```

**connect-distributed.properties:**
```
bootstrap.servers=10.xx.xx.xx:9090,10.xx.xx.xx:9090
group.id=connect-cluster

key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://10.xx.xx.xx:8081

value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://10.xx.xx.xx:8081

internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

offset.storage.topic=connect-offsets
config.storage.topic=connect-configs
status.storage.topic=connect-status

```

The Schema Registry log shows that it received a request for `/subjects/[topicname]-value` , but returned 404.
We use Schema Registry for long now, but nowhere in its request logs I have ever seen a request for anything like `/subjects/[topicname]-value`

**Comment by ewencp** [comment] 2017-01-04 00:23
The `AvroConverter` uses a slightly different path in the deserializer because we need to pass version information along with the schema so connectors can properly handle schema changes. The URL you're seeing accessed is for looking up the schema in that subject, including its version. The 40403 error code indicates it really is that the schema isn't being found.

It's not clear to me why it would fail to find it. It is possible something is getting mangled when parsed and so it is not finding the exact match and returns the 404. What version are you using? And is it possible to see what schema is causing the problem (e.g. can you just list what schemas are in that topic)?

**Comment by dhamilton** [comment] 2017-01-04 17:17
I am seeing the same error on my deployment as well. We have two topics with identical schemas, I am able to schedule a connector successfully on one of the topics, but see this error when scheduling on the other topic. Browsing the schema registry seems to show the schemas are properly registered and am able to use the avro console consumer for both. I am running Kafka 0.10.0.1 and schema registry version 3.0.1. Are there any reports of this issue?

**Comment by zoltan-fedor** [comment] 2017-01-04 21:33
Thanks @ewencp for the reply.

Apologies, it seems I might have copied in the wrong error code. While I have seen 40403 errors, those could be explained. For those the schema was missing. The puzzling ones are the 40401 codes, see below.

```
[2017-01-04 20:46:21,974] ERROR Task ES-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
org.apache.kafka.connect.errors.DataException: Failed to deserialize data to Avro: 
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:109)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:358)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:239)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.SerializationException: **Error retrieving Avro schema for id 441**
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: **Subject not found.; error code: 40401**
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:170)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:187)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:215)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:206)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:200)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getVersionFromRegistry(CachedSchemaRegistryClient.java:69)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getVersion(CachedSchemaRegistryClient.java:161)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:149)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:190)
	at io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:130)
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:99)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:358)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:239)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

We are using Schema Registry version 3.1.1 (confluent-schema-registry-3.1.1-1), upgraded from 2.0.1 last month.

I have manually tried to make the same queries from Schema Registry to see what's going on:

1. When I list all the subjects, I do see the subject in question ("apphits"):
```
$ curl --noproxy '*' 10.xx.xx.xx:8081/subjects
["adc","opsconsole","apphits"]
```

2. I can query the schema id with no problem:
```
$ curl --noproxy '*' 10.xx.xx.xx:8081/schemas/ids/441
{"schema":"{\"type\":\"record\",\"name\":\"apphits\",\"namespace\":\"python.apphits.v1\",\"doc\":\"apphits schema v1\",\"fields\":[{\"name\":\"ProductCode\", ...
```

3. But I cannot query the subjects/[topic]-value record (would it be POST??):
```
$ curl --noproxy '*' 10.xx.xx.xx:8081/subjects/apphits-value
{"error_code":405,"message":"HTTP 405 Method Not Allowed"}
```

4. Nothing for `subjects/[topic]-values/versions` either
```
$ curl --noproxy '*' 10.xx.xx.xx:8081/subjects/apphits-value/versions
{"error_code":40401,"message":"Subject not found."}
```

5. But without "-value" it works:
```
curl --noproxy '*' 10.xx.xx.xx:8081/subjects/apphits/versions
[1]
```

```
$ curl --noproxy '*' 10.xx.xx.xx:8081/subjects/apphits/versions/1
{"subject":"apphits","version":1,"id":441,"schema":"{\"type\":\"record\",\"name\":\"apphits\",\"namespace\":\"python.apphits.v1\",\"doc\":\"apphits schema v1\",\"fields\":[{\"name\": [...]
```

Honestly, I didn't even know that there is such an endpoint (`/subjects/[topic]-value`) in the Schema Registry - we use Schema Registry since version 1.0.1 and never the logs have shown such endpoint being accessed. I just looked it up in the API docs, which only provides a short reference http://docs.confluent.io/1.0/schema-registry/docs/api.html#subjects

Is this "/subjects/[topic]-value" endpoint new? We are not having those, so is it possible that the upgrade of Schema Registry not covering it?

**Comment by SUJIESHN** [comment] 2017-02-25 13:45
Hi, 
I am getting the same error 
[2017-02-25 08:38:37,576] INFO WorkerSinkTask{id=cassandra-sink-edison-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:262)
[2017-02-25 08:38:37,615] ERROR Task cassandra-sink-edison-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
org.apache.kafka.connect.errors.DataException: Failed to deserialize data to Avro:
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:109)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:358)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:239)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id 281
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema not found; error code: 40403
        at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:170)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:187)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:323)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:316)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaByIdFromRegistry(CachedSchemaRegistryClient.java:63)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getBySubjectAndID(CachedSchemaRegistryClient.java:118)
        at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:121)
        at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:190)
        at io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:130)
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:99)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:358)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:239)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

I am reading from a sql server through a jdbc connector and writing into a cassandra table using sink connector.  The sink is giving me the above error.  It was working fine couple of days before.

Thanks,
Sujiesh

**Comment by Nilkanthpatel04** [comment] 2017-03-30 07:34
With confluent-3.0.0, I am getting the similar error. Do we have a workaround for this.

org.apache.kafka.connect.errors.DataException: Failed to deserialize data to Avro: 
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:109)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:345)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:226)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id 1
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema not found; error code: 40403
        at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:164)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:181)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:209)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:200)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.lookUpSubjectVersion(RestService.java:194)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getVersionFromRegistry(CachedSchemaRegistryClient.java:67)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getVersion(CachedSchemaRegistryClient.java:134)
        at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:148)
        at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserializeWithSchemaAndVersion(AbstractKafkaAvroDeserializer.java:189)
        at io.confluent.connect.avro.AvroConverter$Deserializer.deserialize(AvroConverter.java:130)
        at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:99)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:345)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:226)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by zoltan-fedor** [comment] 2017-03-30 14:55
Unfortunately I did not find a workaround, so I have abandoned this.
I am now building my own kafka-to-elasticsearch interface.

**Comment by ewencp** [comment] 2017-04-06 00:15
The subjects you are using don't seem to correspond to the format used by the Confluent serializers. These should be setting the subjects as `<topic>-<key>` and `<topic>-<value>`. If you are using the *old* producer and consumer, then they will fall back to using just `<topic>` since those interfaces cannot distinguish between key and value. However, if you want to use any of the compatibility functionality of the schema registry, then you'd need to either need to use the new producer/consumer or never use keys.

The reason you are seeing this issue (assuming my above analysis is correct) is that Connect *only* uses the new producer and consumer and assumes you do as well. In order to allow connectors to reason intelligently about schema changes, Connect allows schema version info to be included from the underlying serialization format. In this case, the deserializer adds an extra step compared to normal serialization to get this information. However, it makes the assumptions I stated, so when it reads a value from topic `apphits` it is trying to lookup the version from `apphits-value` (and the same for keys and `apphits-key`).

In terms of workarounds, there aren't any really good options (we *highly* encourage moving to new producer/consumer). One possibility, however, is to simply duplicate the schemas in `apphits` into `apphits-value` as well, which will allow the version lookup to return successfully.

**Comment by nicktoker** [comment] 2017-11-22 07:07
i had the same problem , i use schema-registry 3.3.0
the problem was diffidence between the producer and consumer "schema.registry.url"
in the producer i used hostname ( http://hostname:8081) and in the consumer an IP address ( for example http://192.168.3.2:8081)
i changed both user host name (e.g. to be the same)  and it solve the problem
hope it helps

**Comment by gavinmcnair** [comment] 2017-12-14 13:22
With the schema-registry 3.3.0 i am still having a similar problem.

In the schema registry log i am still seeing 404 messages 

--
[2017-12-14 11:56:21,048] INFO 10.92.204.28 - - [14/Dec/2017:11:56:21 +0000] "GET /schemas/ids/6 HTTP/1.1" 200 10550  25 (io.confluent.rest-utils.requests)
[2017-12-14 11:56:21,405] INFO 10.92.204.28 - - [14/Dec/2017:11:56:21 +0000] "POST /subjects/view-message-value?deleted=true HTTP/1.1" 404 49  298 (io.confluent.rest-utils.requests)
--
Even though we do have view-message-value in the registry.
--
[2017-12-14 13:20:43,276] INFO 10.92.204.32 - - [14/Dec/2017:13:20:43 +0000] "GET /subjects/view-message-value/versions/6 HTTP/1.1" 200 5494  27 (io.confluent.rest-utils.requests)
--

I am a bit stuck. Is our schema topic corrupt?

**Comment by laoyang360** [comment] 2019-05-23 08:33
In confluent 3.3.0 , I have the same error.

`[2019-05-23 16:10:45,002] ERROR Unknown error when running consumer:  (kafka.tools.ConsoleConsumer$:105)
org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id 121
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema not found; error code: 40403
        at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:182)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:203)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:379)
        at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:372)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaByIdFromRegistry(CachedSchemaRegistryClient.java:65)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getBySubjectAndId(CachedSchemaRegistryClient.java:131)
        at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:122)
        at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:93)
        at io.confluent.kafka.formatter.AvroMessageFormatter.writeTo(AvroMessageFormatter.java:122)
        at io.confluent.kafka.formatter.AvroMessageFormatter.writeTo(AvroMessageFormatter.java:107)
        at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:140)
        at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:78)
        at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:53)
        at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)`

but when i exec: 
```
 curl -X GET "http://10.18.46.25:8081/subjects/input_wde_golaxy-key/versions/latest"
{"subject":"input_xxx-key","version":1,"id":121,"schema":"\"string\""}
```

**Comment by NathanNam** [comment] 2019-06-13 23:34
Is this still an issue with CP 5.x?

**Comment by ParhamZare** [comment] 2019-12-02 07:42
I have the same issue in "CP 5.3.1" the subject registered  with "-value" suffix

**Comment by cricket007** [comment] 2019-12-10 02:52
This isn't an issue with Elasticsearch connector.

You can simulate the same error with the Avro console consumer along with the print.keys=true property

**Comment by levzem** [comment] 2020-02-14 00:19
closing because issue with SR

**Closed by levzem** 2020-02-14 00:19 UTC
Labels: question, wait info

**Comment by shahgunjan07** [comment] 2022-08-18 17:57
> With the schema-registry 3.3.0 i am still having a similar problem.
> 
> In the schema registry log i am still seeing 404 message on the post. Another totally different topic seems to work fine.
> 
> ```
> [2017-12-14 11:56:21,048] INFO IP - - [14/Dec/2017:11:56:21 +0000] "GET /schemas/ids/6 HTTP/1.1" 200 10550  25 (io.confluent.rest-utils.requests)
> [2017-12-14 11:56:21,405] INFO IP - - [14/Dec/2017:11:56:21 +0000] "POST /subjects/view-message-value?deleted=true HTTP/1.1" 404 49  298 (io.confluent.rest-utils.requests)
> ```
> 
> Even though we do have view-message-value in the registry.
> 
> ```
> [2017-12-14 13:20:43,276] INFO IP - - [14/Dec/2017:13:20:43 +0000] "GET /subjects/view-message-value/versions/6 HTTP/1.1" 200 5494  27 (io.confluent.rest-utils.requests)
> ```
> 
> I am a bit stuck. Is our schema topic corrupt?

I am facing similar issue with confluent dockers image version 7.2.0. Let me know if anyone has found any solution.

**Comment by big-thousand** [comment] 2022-12-02 18:07
I notice that maybe it's cased by json key sort

I have test for redpanda

```shell
# work
curl --location --request POST 'http://redpanda-cluster-0.redpanda-cluster.redpanda-cluster-default.svc.cluster.local:8081/subjects/tidb_v_user-value?normalize=false&deleted=true' \
--header 'Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2' \
--header 'Cache-Control: no-cache' \
--header 'Connection: keep-alive' \
--header 'Content-Length: 1311' \
--header 'Content-Type: application/vnd.schemaregistry.v1+json' \
--header 'Pragma: no-cache' \
--header 'User-Agent: Java/11.0.14.1' \
--data-raw '{"schema":"{\"type\":\"record\",\"name\":\"user\",\"namespace\":\"default.v\",\"fields\":[{\"name\":\"biz_id\",\"type\":{\"type\":\"long\",\"connect.parameters\":{\"tidb_type\":\"BIGINT UNSIGNED\"}}},{\"name\":\"user_id\",\"type\":{\"type\":\"long\",\"connect.parameters\":{\"tidb_type\":\"BIGINT UNSIGNED\"}}},{\"name\":\"user_name\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TEXT\"}}},{\"default\":\"\",\"name\":\"avatar\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TEXT\"}}},{\"default\":\"\",\"name\":\"description\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TEXT\"}}},{\"default\":0,\"name\":\"gender\",\"type\":{\"type\":\"int\",\"connect.parameters\":{\"tidb_type\":\"INT\"}}},{\"default\":\"\",\"name\":\"phone_number\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TEXT\"}}},{\"default\":\"CURRENT_TIMESTAMP\",\"name\":\"ctime\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TIMESTAMP\"}}},{\"default\":\"CURRENT_TIMESTAMP\",\"name\":\"mtime\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TIMESTAMP\"}}},{\"default\":\"CURRENT_TIMESTAMP\",\"name\":\"btime\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TIMESTAMP\"}}}]}"}'
```

```
# not work
curl --location --request POST 'http://redpanda-cluster-0.redpanda-cluster.redpanda-cluster-default.svc.cluster.local:8081/subjects/tidb_v_user-value?normalize=false&deleted=true' \
--header 'Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2' \
--header 'Cache-Control: no-cache' \
--header 'Connection: keep-alive' \
--header 'Content-Length: 1311' \
--header 'Content-Type: application/vnd.schemaregistry.v1+json' \
--header 'Pragma: no-cache' \
--header 'User-Agent: Java/11.0.14.1' \
--data-raw '{"schema":"{\"type\":\"record\",\"name\":\"user\",\"namespace\":\"default.v\",\"fields\":[{\"name\":\"biz_id\",\"type\":{\"type\":\"long\",\"connect.parameters\":{\"tidb_type\":\"BIGINT UNSIGNED\"}}},{\"name\":\"user_id\",\"type\":{\"type\":\"long\",\"connect.parameters\":{\"tidb_type\":\"BIGINT UNSIGNED\"}}},{\"name\":\"user_name\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TEXT\"}}},{\"default\":\"\",\"name\":\"avatar\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TEXT\"}}},{\"default\":\"\",\"name\":\"description\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TEXT\"}}},{\"default\":0,\"name\":\"gender\",\"type\":{\"type\":\"int\",\"connect.parameters\":{\"tidb_type\":\"INT\"}}},{\"default\":\"\",\"name\":\"phone_number\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TEXT\"}}},{\"default\":\"CURRENT_TIMESTAMP\",\"name\":\"ctime\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TIMESTAMP\"}}},{\"default\":\"CURRENT_TIMESTAMP\",\"name\":\"mtime\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TIMESTAMP\"}}},{\"default\":\"CURRENT_TIMESTAMP\",\"name\":\"btime\",\"type\":{\"type\":\"string\",\"connect.parameters\":{\"tidb_type\":\"TIMESTAMP\"}}}]}"}'
```

the json schema is equal after format for two request

But the first one is the true schema, the second one sort json keys
