### ISSUE TITLE
Json format Exception,MalformedJsonException

### ISSUE THREAD

**Issue by lbh375441316** [confluentinc/kafka-connect-elasticsearch#68] opened 2017-02-22 08:59 UTC
Hi,

I hive use kafka connector to write data to es,kafka version is 0.10.1.1 and es version is 5.2.1,but when i start connect-standalone i hive get a error:
[pool-1-thread-1] ERROR org.apache.kafka.connect.runtime.WorkerTask - Task kafka-to-elasticsearch-1-0 threw an uncaught and unrecoverable exception
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
at com.google.gson.JsonParser.parse(JsonParser.java:65)
at com.google.gson.JsonParser.parse(JsonParser.java:45)
at io.searchbox.action.AbstractAction.parseResponseBody(AbstractAction.java:94)
at io.searchbox.action.AbstractAction.createNewElasticSearchResult(AbstractAction.java:65)
at io.searchbox.action.GenericResultAbstractAction.createNewElasticSearchResult(GenericResultAbstractAction.java:20)
at io.searchbox.client.http.JestHttpClient.deserializeResponse(JestHttpClient.java:131)
at io.searchbox.client.http.JestHttpClient.execute(JestHttpClient.java:50)
at io.confluent.connect.elasticsearch.ElasticsearchWriter.createIndicesForTopics(ElasticsearchWriter.java:248)
at io.confluent.connect.elasticsearch.ElasticsearchSinkTask.open(ElasticsearchSinkTask.java:113)
at org.apache.kafka.connect.runtime.WorkerSinkTask.openPartitions(WorkerSinkTask.java:431)
at org.apache.kafka.connect.runtime.WorkerSinkTask.access$1000(WorkerSinkTask.java:55)
at org.apache.kafka.connect.runtime.WorkerSinkTask$HandleRebalance.onPartitionsAssigned(WorkerSinkTask.java:467)
at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.onJoinComplete(ConsumerCoordinator.java:228)
at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:313)
at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:277)
at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:259)
at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1013)
at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:979)
at org.apache.kafka.connect.runtime.WorkerSinkTask.pollConsumer(WorkerSinkTask.java:317)
at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:235)
at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:172)
at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:143)
at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1573)
at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1423)
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:546)
at com.google.gson.stream.JsonReader.peek(JsonReader.java:429)
at com.google.gson.JsonParser.parse(JsonParser.java:60)
... 28 more
[pool-1-thread-1] ERROR org.apache.kafka.connect.runtime.WorkerTask - Task is being killed and will not recover until manually restarted

# and my connector conf is :
bootstrap.servers=es-1:9092
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=true
value.converter.schemas.enable=true
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
offset.storage.file.filename=/tmp/connect.offsets
offset.flush.interval.ms=10000

# also the connector sink conf is :
name=kafka-to-elasticsearch-1
connector.class=io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
tasks.max=1
topics=connect-test-3
topic.index.map=connect-test-3:myindex
key.ignore=true
topic.schema.ignore=ture
connection.url=http://es-2:9200,http://es-3:9200
type.name=kafka-connect

and who can tell what the problem is .thanks

**Comment by fernandoabcampos** [comment] 2017-05-08 08:30
Hi, @lbh375441316 
Did you manage to solve this issue?
Thanks,

**Comment by yaimag** [comment] 2017-06-17 16:17
Hi @lbh375441316 and @fernandoabcampos 
Any of you could solve this issue? Did you know the cause?
Thanks!

**Comment by ewencp** [comment] 2017-07-11 22:33
Hard to say what the issue is since this this is coming from the underlying library and indicates that ES is returning an invalid JSON response. Are there any other messages in the log before the exception? Without more info about what is being returned in the request it'll be hard to get to the root cause.

**Comment by chaokunyang** [comment] 2017-08-02 08:33
I had the same problem. It is the problem of jest client version and es version in my project.  Jest client used in connector is 2.0.0, it doesn't support es 5.x, ex: create index in ex5.x use put not post. So I can't get more info about what is being returned in the request, because jest directly parse the reponse and don't catch not checked exception:
io.searchbox.action.AbstractAction#parseResponseBody(line 98)
```java
 protected JsonObject parseResponseBody(String responseBody) {
        if (responseBody == null || responseBody.trim().isEmpty()) {
            return new JsonObject();
        }

        JsonElement parsed = new JsonParser().parse(responseBody);
        if (parsed.isJsonObject()) {
            return parsed.getAsJsonObject();
        } else {
            throw new JsonSyntaxException("Response did not contain a JSON Object");
        }
    }
```
if parse like this,there will be more logs:
```java
        JsonElement parsed;
        try {
            parsed  = new JsonParser().parse(responseBody);
        }catch (JsonSyntaxException e) {
            throw new RuntimeException("Can't parse response[" + responseBody + "]", e);
        }
```

**Comment by novakov-alexey** [comment] 2017-08-02 09:51
I had similar issue a couple of month ago when moving to new ES version. Try to use 
jestVersion = "2.4.0"
"io.searchbox"  % "jest" % jestVersion

**Comment by levzem** [comment] 2019-12-20 22:05
closing because connector runs on newer jest version now

**Closed by levzem** 2019-12-20 22:05 UTC
