### ISSUE TITLE
How to config this to ignore bad formatted records?

### ISSUE THREAD

**Issue by ttyao** [confluentinc/kafka-connect-elasticsearch#201] opened 2018-04-30 18:45 UTC
Hi, I am consuming json formatted data from kafka stream nicely, however there are some cases where kafka will output random records in plain text format to the topic. Whenever this happens, the whole task will fail and not be able to continue.  Is there a way to config it to ignore mal-formatted records?

```
[2018-04-22 03:50:03,223] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:172)
org.apache.kafka.connect.errors.DataException: Converting byte[] to Kafka Connect data failed due to serialization error:
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:334)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:468)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:301)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'fdsfs': was expecting 'null', 'true', 'false' or NaN
 at [Source: (byte[])"fdsfs"; line: 1, column: 11]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'fdsfs': was expecting 'null', 'true', 'false' or NaN
 at [Source: (byte[])"fdsfs"; line: 1, column: 11]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:673)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3526)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3502)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._matchToken2(UTF8StreamJsonParser.java:2837)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._matchFalse(UTF8StreamJsonParser.java:2790)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:804)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:723)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4030)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2559)
	at org.apache.kafka.connect.json.JsonDeserializer.deserialize(JsonDeserializer.java:50)
	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:332)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:468)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:301)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:205)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:173)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:214)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2018-04-22 03:50:03,224] ERROR WorkerSinkTask{id=elasticsearch-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:173)
```

**Comment by rhauch** [comment] 2018-04-30 19:15
Check that you're using the correct converters. Perhaps the Connect worker was configured to use the ByteArrayConverter or the AvroConverter? You can either change it there (if it doesn't impact other connectors), or you can define the `key.converter`, `value.converter`, and any additional properties that go along with those given the particular converter you want to use.

For example, if you want to use the JsonConverter, you might do something like this:

```
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
```

where the `schemas.enable` tells the JsonConverter to not look for a schema+payload pair in the message and to instead just assume the message is the whole value.

**Comment by ttyao** [comment] 2018-04-30 21:15
@rhauch  Yes, I am using the exact JsonConverter as you mentioned in the reply.
```
key.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
```
And all the normal records like `{"timestamp":"2018-04-29T12:34:56Z", "severity":"info"}` can be processed properly. However, in my case kafka topic will also receive something in non-json format, like "SERVER restarted at xxx", although I know ideally this shouldn't happen, but I am just wondering if there is a way for kafka-connect-elasticsearch to ignore these and not crash? The current behavior is as long as it receives anything non-json, it will throw exception and stop.

**Comment by rhauch** [comment] 2018-04-30 22:18
The latest version of the Elasticsearch connector can be configured with [various behaviors](https://docs.confluent.io/4.1.0/release-notes.html#elasticsearch-connector). However, Connect runs the Converter, and if the Converter is unable to even deserialize the message and convert it into a Connect record, then that happens before the connector even sees it, as demonstrated by your stack trace.

The only workaround, other than having topics with well-formed messages, is to write a custom Converter that attempts to use the JSON converter, and then handles the non-JSON messages accordingly. The community is working on [bad data handing](https://issues.apache.org/jira/browse/KAFKA-6738) to address this, but that's hopefully coming in Apache Kafka 2.0 later this year and is not available now.

**Comment by ttyao** [comment] 2018-04-30 22:30
As Connect runs the Converter, is it possible for Connect to deserialize dataException and swallow it if `behavior.on.malformed.documents` is set to `ignore`?

**Comment by rhauch** [comment] 2018-05-01 14:39
Not at the present time. The pipeline is as follows for sink connectors like Elasticsearch:

1. consume a messages from Kafka topic(s)
1. for each message:
    1. convert (deserialize into Connect-specific structures) the message using the converter
    1. transform the message using the chain of zero or more transforms
1. Send the transformed messages as a batch to the sink connector

Connect is responsible for all of this logic, and only at #3 does it give the chance for the ES connector to do anything with the already converted and transformed messages. In your case, the problem is in #2i where the JSON converter is unable to parse the messages like `SERVER restarted at xxx` since that is not valid JSON.

As I mentioned, the community is working on a solution, but in the meantime you have three options:

a. Prevent non-JSON data from getting on the topic.
b. Implement your own Converter that tries the JSON Converter or converts non-JSON messages into JSON messages.
c. Implement a Kafka consumer interceptor that converts non-JSON messages into JSON messages.

**Comment by t-d-d** [comment] 2018-08-06 07:02
Hi - just ran into this.  Is there any update as to a solution?  Is that tracked elsewhere?

Thanks

**Comment by levzem** [comment] 2019-11-27 22:15
@t-d-d the expectation is that the records in the topic are in the proper JSON format - the only solution is to clean your data as explained above.

Closing this. Please reopen if you have any further questions.

**Closed by levzem** 2019-11-27 22:15 UTC
Labels: question

**Comment by alecomputacao** [comment] 2021-03-03 18:24
Hi,
First, thanks a lot for the opportunity.

In my situation, occur the same error but I'm receive the xml message in the topic.

When I start de kafka-connect to elastic-sink, appear the message:

Caused by: org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'teste': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (byte[])"teste"; line: 1, column: 6]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'teste': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')

Some suggestion?
